project: myproject
application:
  - name: "benthos-http-producer"
    architectures: [linux/amd64, linux/arm64]
    device-types: [mydevice]
    manifest: app/benthos-http-producer/manifest
    images:
      - name: BENTHOS
        image: docker.io/jeffail/benthos:latest
  - name: go-template
    architectures: [linux/amd64, linux/arm64]
    device-types: [mydevice]
    manifest: app/go-template/manifest
    images:
      - name: GOTEMPLATE
        image:  ghcr.io/ci4rail/go-template:pr-pr-check

