project: mender-template
application:
  - name: "benthos-http-producer"
    architectures: [linux/amd64, linux/arm64]
    device-types: [mydevice]
    manifest: app/benthos-http-producer/manifest
    images:
      - name: BENTHOS
        image: docker.io/jeffail/benthos:latest
      - name: GOTEMPLATE
        image:  recorder-app
