version: '3.8'
services:
  benthos_consumer:
    image: jeffail/benthos:latest
    container_name: benthos_consumer
    volumes:
      - ./benthos.yaml:/benthos.yaml
    environment:
      CONSUMER_ADDRESS: "0.0.0.0:32652"
      CONSUMER_PATH: "/post"
    ports:
      - "32652:32652"
    network_mode: host
   